
<?php if ($this->contact): ?>
    <ul class="list-group list-group-unbordered" style="margin-bottom: 0;">
            <li class="list-group-item">
                <i class="fa fa-at"></i><b> Email</b><a class="pull-right">
               <?php echo ($this->contact->getEmail())?$this->contact->getEmail():""; ?>  
                </a>
            </li>
        


            <li class="list-group-item">
                <i class="fa fa-phone"></i><b> Tel</b>  
                <a class="pull-right">
                     <?php echo ($this->contact->getPhone())?$this->contact->getPhone():""; ?>
                    </a>
            </li>
      

        <?php if ($this->contact->getSkype()): ?>
            <li class="list-group-item">
                <i class="fa fa-skype"></i> <b> Skype</b>
                <a class="pull-right">
                    <?php echo $this->contact->getSkype(); ?>
                </a>
            </li>
        <?php endif; ?>

    </ul>
<?php else: ?>
    <ul class="list-group list-group-unbordered" style="margin-bottom: 0;">

        <li class="list-group-item">
            <i class="fa fa-at"></i><b> Email</b><a class="pull-right">
            </a>
        </li>

        <li class="list-group-item">
            <i class="fa fa-phone"></i><b> Tel</b>  <a class="pull-right">
            </a>
        </li>

        <li class="list-group-item">
            <i class="fa fa-skype"></i> <b> Skype</b><a class="pull-right">
            </a>
        </li>


    </ul>

<?php endif; ?>
