<?php if ($this->education): ?>
    <ul class="list-group list-group-unbordered" style="margin-bottom: 0;">
            <li class="list-group-item">
                <i class="fa fa-graduation-cap"></i><b> Nivel Academico</b><a class="pull-right">
               <?php echo ($this->education->getEducation())?$this->education->getEducation():""; ?>
               <?php echo ($this->education->getEducationState())?$this->education->getEducationState():""; ?> 
                </a>
            </li>
    </ul>
<?php else: ?>
    <ul class="list-group list-group-unbordered" style="margin-bottom: 0;">

       <li class="list-group-item">
                <i class="fa fa-at"></i><b> Nivel Academico</b><a class="pull-right">
                </a>
            </li>
    </ul>
<?php endif; ?>
