<?php

echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.ico'))
        ->appendStylesheet($this->basePath() . '/shared/centaurus/libraries/font-awesome.css')
        ->appendStylesheet($this->basePath() . '/shared/bootstrap/css/bootstrap.min.css')
        ->appendStylesheet($this->basePath() . '/main/css/basic-template.css')
        ->appendStylesheet($this->basePath() . '/main/css/custom.css')


;
?> 
