
<div id="app">
    <cv></cv>
</div>

<script type="text/x-template" id="cv">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        <div class="box box-primary">
            <div class="box-body box-profile">
                <div class="row">
                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">image</div>
                    <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12"><cv-personal-information></cv-personal-information></div>
                </div>
            </div>
        </div>
    </div>
</script>

<!--Banderas-->
<?php $this->headLink()->prependStylesheet($this->basePath('shared/flag-icon-css-master/css/flag-icon.min.css')) ?>

<!--VueJS-->
<script src="/vue/build.js"></script>
