<?php

$groups = [
    [
        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
        'id' => 'main',
        'title' => null,
        'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
        'fields' => ['company', 'job']
    ],
    [
        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
        'id' => 'desc',
        'title' => null,
        'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
        'fields' => ['description']
    ],
    [
        'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
        'id' => 'dates',
        'title' => null,
        'columns' => \ZfMetal\Commons\Consts::COLUMNS_THREE,
        'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
        'fields' => ['dateFrom', 'dateTo', 'currentJob']
    ],
];

echo $this->renderForm($this->form, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_ONE, $groups);
?>
