<div class="clearfix" >
    
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ">
        <div id="view-cv-skills">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">Categorias</h4>
                </div>
                <div class="panel-body">
                    <?= $this->partial("pi/cv-skill/skill-categories") ?>
                </div>

            </div>

        </div>

    </div>

    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 ">
        <div class="panel panel-default"> 
            <div class="panel-heading">
                <h4 class="panel-title">Explorador de Habilidades</h4>
            </div> 
            <div class="panel-body"> 
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-search"></i></div>
                        <input  id="searchinput" class="form-control" autocomplete="off" type="search" placeholder="Buscar..." />
                    </div>
                </div>
                <div id="searchlist" class="skill-panel">
                    <?php foreach ($this->skillCategories as $skillCategory): ?>
                        <div class="panel panel-default" id="category_<?= $skillCategory->getId();?>">
                            <div class="panel-heading">
                                <h4 class="panel-title"><?php echo $skillCategory->getName(); ?></h4>
                            </div>
                            <div class="panel-body nopadding">
                                <?php if (count($skillCategory->getSkills())): ?>
                                    <?php foreach ($skillCategory->getSkills() as $skill): ?>

                                        <?php if (key_exists($skill->getId(), $cvSkills)): ?>
                                            <?php echo $this->partial('pi/cv-skill/li', array("skill" => $skill, "cvSkill" => $cvSkills[$skill->getId()])); ?>
                                        <?php else: ?>
                                            <?php echo $this->partial('pi/cv-skill/li-empty', array("skill" => $skill)); ?>
                                        <?php endif; ?>

                                    <?php endforeach; ?>
                                <?php endif; ?>

                            </div>

                        </div>


                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>

</div>


<script>
	$('#searchlist').btsListFilter('#searchinput', {itemChild: 'label'});
</script>