<?php

return [
    'navigation' => [
        'default' => [
            [
                'label' => 'Admin',
                'detail' => '',
                'icon' => '',
                'permission' => 'general-admin',
                'route' => 'PI/Cv/Index',
                'uri' => '',
                'pages' => [
                    [
                        'label' => 'Skills',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/Skill/Grid',
                    ],
                    [
                        'label' => 'Skill Categories',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/SkillCategory/Grid',
                    ],
                    [
                        'label' => 'Educación',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/Eductaion/Grid',
                    ],
                    [
                        'label' => 'Estado de Educación',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/EducationState/Grid',
                    ],
                    [
                        'label' => 'Jobs',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/Job/Grid',
                    ],
                    [
                        'label' => 'SoftSkill',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/SoftSkill/Grid',
                    ],
                    [
                        'label' => 'SoftSkillCategory',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/SoftSkillCategory/Grid',
                    ],
                    [
                        'label' => 'Countries',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/Country/Grid',
                    ],
                    [
                        'label' => 'Companies',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/Company/Grid',
                    ],
                    [
                        'label' => 'UserCompany',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/UserCompany/Grid',
                    ],
                    [
                        'label' => 'Job Type',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/JobType/Grid',
                    ],
                    [
                        'label' => 'Job Search',
                        'detail' => '',
                        'icon' => '',
                        'permission' => 'general-admin',
                        'route' => 'PI/JobSearch/Grid',
                    ],
                ],
            ],
            [
                'label' => 'CV',
                'detail' => '',
                'icon' => 'fa fa-suitcase',
                'route' => 'PI/CvVue/Main',
            ],
            [
                'label' => 'Buscar Empleo',
                'detail' => '',
                'icon' => 'fa fa-search',
                'uri' => '',
            ],
            [
                'label' => 'Gestionar Busquedas',
                'detail' => '',
                'icon' => 'fa fa-list',
                'uri' => '',
            ],
        ],
    ],
];