

<div class="clearfix"></div>
<div class="col-md-7">
    <div class="box box-solid">
        <div class="box-header">

        </div>
        <!-- /.box-header -->
        <div class="box-body">

        </div>
    </div>
</div>
<div class="col-md-5">
    <div class="box box-solid">
        <!-- /.box-header -->
        <div class="box-body">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="http://placehold.it/900x500/39CCCC/ffffff&amp;text=I+Love+Bootstrap" alt="First slide">

                        <div class="carousel-caption">
                            First Slide
                        </div>
                    </div>
                    <div class="item">
                        <img src="http://placehold.it/900x500/3c8dbc/ffffff&amp;text=I+Love+Bootstrap" alt="Second slide">

                        <div class="carousel-caption">
                            Second Slide
                        </div>
                    </div>
                    <div class="item">
                        <img src="http://placehold.it/900x500/f39c12/ffffff&amp;text=I+Love+Bootstrap" alt="Third slide">

                        <div class="carousel-caption">
                            Third Slide
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="fa fa-angle-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="fa fa-angle-right"></span>
                </a>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>

<div class="clearfix"></div>
<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
    <div class="small-box bg-maroon">
        <div class="inner">
            <h3>Habilitades Técnicas</h3>

            <p>Biblioteca de habilidades en tecnologia, herramientas, protocolos, lenguajes. </p>
        </div>

        <a href="#" class="small-box-footer">
            Ingresar <i class="fa fa-arrow-circle-right"></i>
        </a>
    </div>
</div>


<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
    <div class="small-box bg-green">
        <div class="inner">
            <h3>Puestos IT</h3>

            <p>Biblioteca de puestos/cargos en IT. Descripción de puestos, requisitos, habilidades.</p>
        </div>

        <a href="#" class="small-box-footer">
            Ingresar <i class="fa fa-arrow-circle-right"></i>
        </a>
    </div>
</div>


<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
    <div class="small-box bg-aqua">
        <div class="inner">
            <h3>Cursos</h3>

            <p>Biblioteca de cursos IT. Desarrollo, Networking, Base de Datos, Servidores.</p>
        </div>

        <a href="#" class="small-box-footer">
            Ingresar <i class="fa fa-arrow-circle-right"></i>
        </a>
    </div>
</div>

<div class="clearfix"></div>