    <div class="panel panel-cv" data-toggle="modal" data-target="#cv-contact-modal">
        <div class="panel-heading">
            <h4 class="panel-title">Datos de Contacto</h4>
        </div>
        <div class="panel-body padding5">
            <div id="cv-contact">
                <?php echo $this->partial("pi/cv/partial/contact", ["contact" => $this->cv->getContact()]); ?> 
            </div>
        </div>

    </div>

<!--Modal-->
<div id="cv-contact-modal" class="modal fade " tabindex="-1" role="dialog" >
    <div class="modal-dialog modal-sm" role="document">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Datos de Contacto</h4>
            </div>

            <div class="modal-body">
                <div class="row">

                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <!--FORM-->
                        <div id="form-cv-contact"></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


