
<div id="cv-education" class="hoverHighlight" data-toggle="modal" data-target="#cv-education-modal">
    <?php echo $this->partial("pi/cv/partial/education", ["education" => $this->cv->getEducation()]); ?> 
</div>



<!--Modal-->
<div id="cv-education-modal" class="modal fade " tabindex="-1" role="dialog" >
    <div class="modal-dialog modal-sm" role="document">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Información Academica</h4>
            </div>

            <div class="modal-body">
                <div class="row">

                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <!--FORM-->

                        <div id="form-cv-education">
                            <i class="fa fa-spin fa-spinner"></i>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


