<?php

$this->headScript()->appendFile($this->basePath() . '/shared/jquery-form/jquery.form.js', 'text/javascript')
        ->appendFile($this->basePath() . '/modules/pi/js/cv.js')
        ->appendFile($this->basePath() . '/modules/pi/js/cv-picture.js')
        ->appendFile($this->basePath() . '/modules/pi/js/cv-personal-information.js')
        ->appendFile($this->basePath() . '/shared/list-filter/bootstrap-list-filter.min.js');

$this->headScript()
        ->appendScript($this->partial('pi/cv/js/cv-init.js'), 'text/javascript');
?>

<?php echo $this->partial('pi/cv/cv', array("cv" => $this->cv)); ?>