
<div id="cv-location" class="hoverHighlight" data-toggle="modal" data-target="#cv-location-modal">
    <?php //echo $this->partial("pi/cv/partial/location", ["location" => $this->cv->getLocation()]); ?> 
    <ul class="list-group list-group-unbordered" style="margin-bottom: 0;">

        <li class="list-group-item">
            <i class="fa fa-map-marker "></i><b> Ubicación</b>
            <a class="pull-right">
                Floresta, CABA
            </a>
        </li>

    </ul>

</div>


