<a href="#"  data-toggle="modal" data-target="#cv-picture-modal">
    <div id="cv-picture">
       <?php echo $this->partial("pi/cv/partial/picture",["picture" => $this->cv->getPicture()]); ?>
    </div>
</a>
<div class="clearfix"></div>

<!--Modal-->
<div id="cv-picture-modal" class="modal fade " tabindex="-1" role="dialog" >
    <div class="modal-dialog modal-sm" role="document">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Foto</h4>
            </div>

            <div class="modal-body">
                <div class="row">

                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
                        <!--FORM-->
                        <div id="form-cv-picture"><i class="fa fa-spin fa-spinner"></i></div>
                    </div>

                    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 text-center">
                        <div class="progress progress-striped active margin6">
                            <div id="cv-picture-bar" class="progress-bar progress-bar-warning " role="progressbar" aria-valuenow="0" aria-valuemin="1" aria-valuemax="100" >
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>




