<div class="box box-primary" data-toggle="modal" data-target="#cv-skills-modal">
    <div class="box-header">
         <strong><i class="fa fa-star margin-r-5"></i> Habilidades </strong>
    </div>
    <div class="box-body ">
        <div id="cv-skills">
            <?php echo $this->partial("pi/cv/partial/skills", ["cv" => $this->cv]); ?> 
        </div>
    </div>

</div>


<!--Modal-->
<div id="cv-skills-modal" class="modal fade " tabindex="-1" role="dialog" >
    <div class="modal-dialog modal-lg" role="document">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel"><?php echo $this->translate('Habilidades'); ?></h4>
            </div>

            <div class="modal-body">
                <div class="row">
                    <div id="form-cv-skills">
                        <i class="fa fa-spin fa-spinner"></i>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>



